"""Turn the shared test vectors (vectors/thermaestro-gw.json) into C++ for the host tests."""

import json
import sys
from pathlib import Path

CORE_FIELDS = {
    "flags": "request_flags",
    "data": "frame",
}
BYTES = {"frame", "data"}
ERRORS = {
    "bad_magic": "BAD_MAGIC",
    "bad_version": "BAD_VERSION",
    "unknown_type": "UNKNOWN_TYPE",
    "malformed": "MALFORMED",
    "unsupported_option": "UNSUPPORTED_OPTION",
    "auth_failed": "AUTH_FAILED",
}


def message(m: dict) -> str:
    lines = [
        "tgw::Message m;",
        f"m.type = tgw::MessageType::{m['type']};",
        f"m.id = {m['id']}u;",
        f"m.gw_time_us = {m['gw_time_us']}ull;",
    ]
    for key, value in m["core"].items():
        field = CORE_FIELDS.get(key, key)
        if key in BYTES:
            lines.append(f'm.{field} = test::unhex("{value}");')
        else:
            lines.append(f"m.{field} = {value};")
    for option in m["options"]:
        lines.append(f'm.options.push_back({{{option["tag"]}, test::unhex("{option["value"]}")}});')
    lines.append("return m;")
    return "[] { " + " ".join(lines) + " }"


def main(source: Path, target: Path) -> None:
    v = json.loads(source.read_text())
    out = ["// Generated by gen_vectors.py from vectors/thermaestro-gw.json; don't edit.", ""]
    out.append("static const MessageVector MESSAGE_VECTORS[] = {")
    for entry in v["messages"]:
        out.append(f'    {{"{entry["name"]}", "{entry["hex"]}", {message(entry["message"])}}},')
    out.append("};")
    out.append("")
    out.append("static const InvalidVector INVALID_VECTORS[] = {")
    for entry in v["invalid"]:
        tag = entry.get("tag")
        has_tag = "true" if tag is not None else "false"
        out.append(
            f'    {{"{entry["name"]}", "{entry["hex"]}", tgw::ErrorCode::{ERRORS[entry["error"]]}, '
            f"{has_tag}, {tag or 0}}},"
        )
    out.append("};")
    out.append("")
    auth = v["auth"]
    out.append("static const AuthVectors AUTH = {")
    for key in ("psk", "client_nonce", "gateway_nonce"):
        out.append(f'    "{auth[key]}",')
    out.append(f"    {auth['boot_id']}u,")
    out.append(f'    "{auth["session_key"]}",')
    out.append("};")
    out.append("")
    out.append("static const SignedVector SIGNED_VECTORS[] = {")
    for entry in auth["signed"]:
        out.append(
            f'    {{"{entry["name"]}", "{entry["key"]}", {entry["seq"]}u, "{entry["hex"]}", true}},'
        )
    for entry in auth["bad"]:
        out.append(f'    {{"{entry["name"]}", "{entry["key"]}", 0u, "{entry["hex"]}", false}},')
    out.append("};")
    target.write_text("\n".join(out) + "\n")


if __name__ == "__main__":
    main(Path(sys.argv[1]), Path(sys.argv[2]))
